# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ovw < Formula
  desc "A terminal overview for your local projects."
  homepage "https://github.com/roie/ovw"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roie/ovw/releases/download/v1.0.1/ovw_1.0.1_darwin_amd64.tar.gz"
      sha256 "a5c953fa89ab5e76d7b5ab9d05cfddda9ee00c1bd73ea3fef9579fa3340f30f1"

      define_method(:install) do
        bin.install "ovw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roie/ovw/releases/download/v1.0.1/ovw_1.0.1_darwin_arm64.tar.gz"
      sha256 "ac6c088444c48b1e16501fe06c7891646ba300fa015571199fe4db9e116e09be"

      define_method(:install) do
        bin.install "ovw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roie/ovw/releases/download/v1.0.1/ovw_1.0.1_linux_amd64.tar.gz"
      sha256 "ed8b1a925b8c02ec97a7582271e1fd6dd2c8751a198244487d22f878669ba28d"
      define_method(:install) do
        bin.install "ovw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roie/ovw/releases/download/v1.0.1/ovw_1.0.1_linux_arm64.tar.gz"
      sha256 "5a340f44ea95a9892872269a6ec557f1e8d2d78379cfcc6eb06cacdeeb9014e5"
      define_method(:install) do
        bin.install "ovw"
      end
    end
  end

  test do
    system "#{bin}/ovw", "--version"
  end
end
