# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ovw < Formula
  desc "A terminal overview for your local projects."
  homepage "https://github.com/roie/ovw"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roie/ovw/releases/download/v1.1.0/ovw_1.1.0_darwin_amd64.tar.gz"
      sha256 "3f4aa569ef9726d880741034ba76d6322827ebc587c3d872dfd6ee915eca2a20"

      define_method(:install) do
        bin.install "ovw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roie/ovw/releases/download/v1.1.0/ovw_1.1.0_darwin_arm64.tar.gz"
      sha256 "f46a9588c41f8bfaf1b2f1f2917587a3279bfb4e0e9c7cd90cc993d1fa103057"

      define_method(:install) do
        bin.install "ovw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roie/ovw/releases/download/v1.1.0/ovw_1.1.0_linux_amd64.tar.gz"
      sha256 "883c472873e9bfea7b5c000199281552d20f3dd193794497c29cc35ec8ccd9c7"
      define_method(:install) do
        bin.install "ovw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roie/ovw/releases/download/v1.1.0/ovw_1.1.0_linux_arm64.tar.gz"
      sha256 "30d9cc0c565850cc95b1e0481effb489f79b82807c12f624cc52e302b353cd03"
      define_method(:install) do
        bin.install "ovw"
      end
    end
  end

  test do
    system "#{bin}/ovw", "--version"
  end
end
